import type { NextPage } from 'next'
import React from "react"
import Head from 'next/head'
import Image from 'next/image'
import PagesLayouts from '../layouts/PagesLayouts'
import SectionLayouts from '../layouts/SectionLayouts'
import packageOne from "../public/images/hero.png"

const Home: NextPage = () => {
	return (
		<React.Fragment>
			<Head>
				<title>Delivery App</title>
				<meta name="description" content="Generated by create next app" />
				<meta http-equiv="Content-Type" content="text/html;charset=UTF-8" />
				<meta http-equiv="X-UA-Compatible" content="IE-Edge, chrome" />
				<meta name="keywords" content="delivery app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<div className="background mx-auto w-full max-w-[1440px]">
				<PagesLayouts>
					<SectionLayouts>
						<div className="mt-[80px] flex items-center justify-between">
							<div className="w-[50%]">
								<p className='text-[#6D70BF] mb-3 font-medium text-sm'>Send a package is very easy</p>
								<h1 className='leading-normal font-extrabold text-white text-4xl'>Send Package Easly Only With Delivery.</h1>
								<h3 className='leading-normal mt-4 mb-8 font-normal text-[#999beb] text-[18px]'>Delivery is help you to send some package to your destinations. Sending process is very fast and safety.</h3>
								<button className="font-medium text-md no-underline inline-block bg-[#6D70BF] text-white border-none text-sm px-4 py-3 mr-3 leading-none  border rounded-md  hover:border-transparent mt-4 sm:mt-0">Send  Package Now</button>
								<button className="font-medium text-md no-underline ml-4 inline-block bg-[#14153883] text-blue-300 border-none text-sm px-4 py-3 mr-3 leading-none  border rounded-md  hover:border-transparent mt-4 sm:mt-0">Read more</button>
							</div>
							<div className="w-[50%] flex justify-center relative">
								<div className="w-[300px] ml-[70px]">
									<Image className=' object-cover absolute z-30 left-0' src={packageOne} />
								</div>
								<div className="border border-blue-200 z-20 absolute top-[-60px] right-0 rounded-lg h-[300px] w-[300px]"></div>
							</div>
						</div>
					</SectionLayouts>
				</PagesLayouts>
			</div>
		</React.Fragment >
	)
}

export default Home
